AboutとCoursesの作成
RyomaOhtani/frontend-basic-site pull request #2
Opened 2024-04-01 00:08 UTC by RyomaOhtani

結構雑になってしまった自覚があるので、細かいところでも指摘いただけると幸いです。
よろしくお願いします。

2024-04-01 14:34 UTC, masato626 commented
全体は悪くない！一点だけ修正お願いします🙇‍♀️

2024-04-01 15:06 UTC, masato626 commented on style.css
> +}
<img width="492" alt="スクリーンショット 2024-04-01 23 35 07" src="https://github.com/RyomaOhtani/frontend-basic-site/assets/108778037/fd0a4127-8f0d-4728-aed3-5df77a19c1e4">
このように画面幅が小さくなった時に、コースの部分が背景からはみ出てるから、ここのクラスに親クラスの幅に合わせるようにスタイルを追加してみてください✌️（1行追加で済むよ！）

2024-04-02 07:58 UTC, masato626 commented on style.css
> +}
はみ出しは直ってるんだけど、今回はpaddingを適応させたいので、そこの幅まで調整してくれるwidthプロパティを.courses-wrapperにつけてあげてください！
over-flow:hidden;だとcoursesからはみ出したものに適応されるけど、paddningがその子クラスのcourses-wrapperについているので、そっちで調整してください👍

2024-04-03 02:05 UTC, RyomaOhtani commented
横幅250pxくらいまでなら崩れずにpaddingが適応されます
これ以下はどうにもできませんでした、、、

2024-04-06 01:21 UTC, higashiji2000 requested changes

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  overflow: hidden;
![image](https://github.com/RyomaOhtani/frontend-basic-site/assets/83479175/b52ef3dd-ac37-4da2-b4df-7beadd476582)

ボタンにホバーしたとき、はみ出したぶんが隠れてしまっているので修正をお願いします。

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  height: 60px;
![image](https://github.com/RyomaOhtani/frontend-basic-site/assets/83479175/7f91b0c5-def8-4057-b5a9-ae0add1e0c28)

カードとボタンの幅が同じになるようにしてください。（Figma参照）
Developer Tool を使って画面幅を変えて調べてみるのが良いかと思います。

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  background: var(--background-black, #171525);
Figmaと背景色が異なっているため、修正をお願いします。

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  background: var(--background-black, #171525);
```suggestion
  background: var(--background-black);
```

第2引数は代替値ですが、今回の場合ファイル上部で定義されていることが確実なので書かなくてよいかと思います。
CSS変数をJavaScriptで動的に書き換えたりする場合に役に立つものという認識です。

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  background: var(--background-black, #171525);
他の部分も同様です。

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  font-family: "Noto Sans";
CSS変数でフォントの値を用意しているので、こちらを使いましょう（ ` --font-family-body` ）
Figmaではなぜか Noto Sans JP ではなく Noto Sans になっているので修正します 🙏

2024-04-06 01:21 UTC, higashiji2000 commented on style.css
> +  font-family: Anton;
こちらもCSS変数に書き換えましょう

2024-04-06 01:21 UTC, higashiji2000 commented on index.html
> +            </div>
```suggestion
        <h2 class="course-title">Courses</h2>
        <div class="course-cards">
          <a href="" class="course-card">
            <div class="course-card-title-img">
              <h3 class="course-card-title">Frontman</h3>
            </div>
```
細かいところですが、階層構造としてはこちらが適切かと思います。

2024-04-06 01:24 UTC, higashiji2000 commented
> 横幅300pxくらいまでなら崩れずにpaddingが適応されます
これ以下はどうにもできませんでした、、、

初代 iPhoneSE が 320px, 2代目SEが 375px なので、それ以下の幅については対応の必要がないと考えて良いと思います。
参考：https://www.genz.jp/useful_information/iphone_size_quickreferencematrix/

2024-04-07 06:36 UTC, higashiji2000 approved these changes
LGTM 💇

2024-04-07 08:14 UTC, merged